name: Test (windows)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  windows-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install VapourSynth
        run: |
          Invoke-WebRequest -Uri "https://github.com/vapoursynth/vapoursynth/releases/download/R70/Install-Portable-VapourSynth-R70.ps1" -OutFile Install-Portable-VapourSynth-R70.ps1
          Invoke-WebRequest -Uri "https://github.com/vapoursynth/vapoursynth/releases/download/R70/Install-Portable-VapourSynth-R70.bat" -OutFile vs.bat
          .\vs.bat -Unattended
          .\vapoursynth-portable\VSPipe.exe --version

      - name: build dll
        run: |
          .\test\build.ps1
          cp .\zig-out\bin\vszip.dll .\vapoursynth-portable\vs-plugins\vszip.dll

      - name: Run test.vpy (8-bit)
        run: .\vapoursynth-portable\VSPipe.exe .\test\test.vpy . -o 1

      - name: Run test.vpy (16-bit)
        run: .\vapoursynth-portable\VSPipe.exe .\test\test.vpy . -o 2

      - name: Run test.vpy (32-bit)
        run: .\vapoursynth-portable\VSPipe.exe .\test\test.vpy . -o 3

      - name: Run rfs_mismatch.py
        run: .\vapoursynth-portable\python.exe .\test\rfs_mismatch.py
